sensor:
  unique_id: "ahc_blueprint_version_latest"
  command: "curl https://raw.githubusercontent.com/panhans/HomeAssistant/refs/heads/main/blueprints/automation/panhans/advanced_heating_control.yaml"
  name: "AHC Blueprint Latest Version"
  value_template: "{{ value | regex_findall('\\*\\*Version\\*\\*:(.+\\d+.\\d+.\\d+)', '\\1') | first | trim }}"
  scan_interval: 3600 # every hour
